### ISSUE TITLE
Allow to display ways on maps.

### ISSUE THREAD

**Issue by bossly** [mapsme/api-android#1]
I want to use maps in my application. But i need to draw polyline over map
![images-1](https://f.cloud.github.com/assets/130861/773747/dd182530-e941-11e2-84ff-1fcdcb2cf926.jpeg)
to display trajectory like this:
![images](https://f.cloud.github.com/assets/130861/773748/dd1a696c-e941-11e2-9df4-65aac4d511ff.jpeg)

propose scheme:
Intent i; // Intent.ACTION_VIEW
//Waypoints
double[] lat = {33.4,8.3,22.2};
double [] lng = {33.4,8.3,22.3};
i.putExtra("lat", lat);
i.putExtra("lng", lng); 
startActivity(i);

**Comment by mbc66** [comment]
Hello....
Are you planned implementation of this feature?

**Comment by mbc66** [comment]
I need this feature. Please help me. Thank you

**Comment by bossly** [comment]
is this closed because it's implemented?
