### ISSUE TITLE
How can I get location that is selected by user?

### ISSUE THREAD

**Issue by anileger** [mapsme/api-android#14]
When I want to show the map on my activity, immediately maps.me application is opened,and how can I get information about user's selected location/point ?

I want to get that "clicked location" information on my activity...

**Comment by melnichek** [comment]
@deathbaba Could you please reply?

**Comment by deathbaba** [comment]
At the moment, there is no API for that. We consider it in the future though.

**Comment by deathbaba** [comment]
Now you can only pass points which were set in your app, and detect when user click on any of them.

**Comment by deathbaba** [comment]
Hm, can you please check this one? https://github.com/mapswithme/api-android/blob/master/lib/src/com/mapswithme/maps/api/MapsWithMeApi.java#L138

**Comment by savinovalex** [comment]
Hey, guys. I wondering the same question. There is API function 'pickPoint' and I couldn't find docs for it. In some reasons I haven't recieved onNewIntent call after picking some points in MWM activity. Please help me!

**Comment by d-kunin** [comment]
@savinovalex how do you create PendingIntent?

**Comment by savinovalex** [comment]
@d-kunin here the test code:

            final Intent i = new Intent(MainActivity.this, MainActivity.class);
            i.putExtra(EXTRA_FROM_MWM, true);
            PendingIntent pintent = PendingIntent.getActivity(MainActivity.this, 0, i, 0);

            ArrayList<MWMPoint> points = new ArrayList<>();
            points.add(new MWMPoint(51.5, 46.0, "Saratov"));
            MwmRequest request = new MwmRequest()
                    .setTitle("title")
                    .setZoomLevel(0.2)
                    .setPendingIntent(pintent)
                    .setCustomButtonName("Whereisyou?")
                    .setPoints(points)
                    .setReturnOnBalloonClick(true);
            MapsWithMeApi.sendRequest(MainActivity.this, request);

**Comment by savinovalex** [comment]
Well it was pretty simple. It been called onCreate method but not the onNewIntent. I'm kind of newbie in Android world.

**Comment by dennis508** [comment]
I would also like to receive information about an arbitrary map point clicked by the user. Not only latitude and longitude but any other available map information, similar to the "Share" operation but in a structured format. Thanks.

**Comment by k3b** [comment]
What about folowing android standards and implement ACTION-PICK returning a [geo-uri](https://tools.ietf.org/html/draft-mayrhofer-geo-uri-00) ? This can be easily tested using the [geo-testgui of the APhotoManager project](https://github.com/k3b/APhotoManager/tree/FDroid/testgui)
