### ISSUE TITLE
integrate maps.me in my android app

### ISSUE THREAD

**Issue by Ketannnn** [mapsme/api-android#27]
How to integrate maps.me in my android app without navigate mapsme app ?
please provide any sdk or library for integrating mapsme.

**Comment by burivuh** [comment]
We have no SDK, only application-level API

**Comment by Ketannnn** [comment]
How to integrate maps.me in my android app without navigate mapsme app ?
Please guide me.

Thanks

**Comment by rexfordnyrk** [comment]
Yes. Is  it possible? have a specific country or location map in my app without having users having to navigate maps.me app. please if possible help...

**Comment by Zverik** [comment]
Sorry, it is not possible.

**Comment by Komzpa** [comment]
@rexfordnyrk for OSM mobile map SDK please have a look at https://getyourmap.com/ GLMap component that does support embedding to apps.

**Comment by rexfordnyrk** [comment]
thanks @Komzpa will check that out.
