### ISSUE TITLE
MAPS.ME API URI not working in Android

### ISSUE THREAD

**Issue by andreddosantos** [mapsme/api-android#31]
Hello guys,

I'm calling the API in IOS with the following URL and all works fine:
`'mapswithme://map?v=1&ll=' + lat + ',' + long;`

Regarding android i cant seem to understand why it does not open.
`'mapswithme://map?v=1&ll=' + lat + ',' + long; // first attempted failed`
`com.mapswithme.maps.pro://map?v=1&ll=' + lat + ',' + long; // second attempted failed`
`com.mapswithme.api://map?v=1&ll=' + lat + ',' + long; // third attempted failed`

can you clarify this? what should be the specific URL for Android.

Regards

**Comment by alexzatsepin** [comment]
Hey @andreddosantos,

Please follow this wiki pages https://github.com/mapsme/api-android/wiki . We don't support mapswithme scheme on android any more. If you have any questions after reading provided wiki please let me now.

**Comment by andreddosantos** [comment]
I'm building an hybrid app, that's why i need it, so i would have to build a plugin to interact natively with the app.

Thank you
