### ISSUE TITLE
API deeplinks no longer work

### ISSUE THREAD

**Issue by cyril23** [mapsme/api-android#33]
The Links described on https://github.com/mapsme/api-android/wiki/Deeplinks no longer work:

Examples documented in the wiki:

- https://dlink.maps.me/map?v=1&ll=54.32123,12.34562&n=Point%20Name&id=AnyStringOrEncodedUrl&backurl=UrlToCallOnBackButton&appname=TitleToDisplayInNavBar
- https://dlink.maps.me/search?query=food&locale=en_US&cll=34.233456,51.345672&map
- https://dlink.maps.me/route?sll=55.800800,37.532754&saddr=PointA&dll=55.760158,37.618756&daddr=PointB&type=vehicle

The App will be opened but without source or destination input.

If you open such links directly in the browser, a Not Found (#404) is returned. Example:
- https://maps.me/map?v=1&ll=54.32123,12.34562&n=Point%20Name&id=AnyStringOrEncodedUrl&backurl=UrlToCallOnBackButton&appname=TitleToDisplayInNavBar
- it seems like in the browser dlink.maps.me redirects to maps.me; but in the end a 404 is returned

**Comment by biodranik** [comment]
@burivuh Can you please comment on this issue?

**Comment by cyril23** [comment]
> @cyril23 please inform: what device model and android version?

Samsung Galaxy S7, Android 8.0.0

**Comment by cfficaurzua** [comment]
This still isn't working 
![image](https://user-images.githubusercontent.com/13381072/203623339-9d855a3a-283a-4294-952b-0c2b00d9820f.png)

**Comment by biodranik** [comment]
@cfficaurzua did you check https://github.com/organicmaps/api-android and https://github.com/organicmaps/api-ios ?
